// Generated by CoffeeScript 1.3.3
(function() {

  define(['jQuery', 'Underscore', 'Backbone', 'views/AppView'], function($, _, Backbone, AppView) {
    var app;
    return app = new Appview;
  });

}).call(this);
