// Generated by CoffeeScript 1.3.3
(function() {
  var AppView, Todo, TodoList, TodoView, Todos, app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Todo = (function(_super) {

    __extends(Todo, _super);

    function Todo() {
      return Todo.__super__.constructor.apply(this, arguments);
    }

    Todo.prototype.defaults = function() {
      return {
        title: "empty todo...",
        order: '',
        done: false
      };
    };

    Todo.prototype.initialize = function() {};

    Todo.prototype.toggle = function() {
      return this.save({
        done: !this.get("done")
      });
    };

    Todo.prototype.clear = function() {
      return this.destroy();
    };

    return Todo;

  })(Backbone.Model);

  TodoList = (function(_super) {

    __extends(TodoList, _super);

    function TodoList() {
      return TodoList.__super__.constructor.apply(this, arguments);
    }

    TodoList.prototype.model = Todo;

    TodoList.prototype.localStorage = new Store("todos-backbone");

    TodoList.prototype.done = function() {
      return this.filter(function(todo) {
        return todo.get("done");
      });
    };

    return TodoList;

  })(Backbone.Collection);

  TodoView = (function(_super) {

    __extends(TodoView, _super);

    function TodoView() {
      return TodoView.__super__.constructor.apply(this, arguments);
    }

    TodoView.prototype.tagName = 'li';

    TodoView.prototype.template = _.template($('#item-template').html());

    TodoView.prototype.events = {
      "click input": "toggleDone",
      "click a.destroy": "clear",
      "dblclick label": "edit",
      "blur .edit": "editDone"
    };

    TodoView.prototype.initialize = function() {
      return this.model.bind('destroy', this.remove, this);
    };

    TodoView.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this;
    };

    TodoView.prototype.edit = function() {
      this.$el.addClass('editing');
      return this.$('.edit').focus();
    };

    TodoView.prototype.editDone = function() {
      return this.$el.removeClass('editing');
    };

    TodoView.prototype.toggleDone = function() {
      return this.model.toggle();
    };

    TodoView.prototype.clear = function() {
      console.log('remove?');
      return this.model.clear();
    };

    return TodoView;

  })(Backbone.View);

  AppView = (function(_super) {

    __extends(AppView, _super);

    function AppView() {
      return AppView.__super__.constructor.apply(this, arguments);
    }

    AppView.prototype.el = $('#todoapp');

    AppView.prototype.events = {
      'keypress #new-todo': 'handleKeypress',
      'click #clear-completed': 'clearCompleted'
    };

    AppView.prototype.initialize = function() {
      Todos.bind('add', this.addTodo, this);
      Todos.bind('reset', this.addAll, this);
      Todos.bind('all', this.render, this);
      return Todos.fetch();
    };

    AppView.prototype.render = function() {
      return console.log("all?");
    };

    AppView.prototype.addAll = function() {
      return Todos.each(this.addTodo);
    };

    AppView.prototype.handleKeypress = function(e) {
      if (e.keyCode === 13) {
        Todos.create({
          title: $(e.target).val()
        });
        return $(e.target).val("");
      }
    };

    AppView.prototype.addTodo = function(model) {
      var view;
      view = new TodoView({
        model: model
      });
      return this.$('#todo-list').append(view.render().el);
    };

    AppView.prototype.clearCompleted = function() {
      return _.each(Todos.done(), function(todo) {
        return todo.destroy();
      });
    };

    return AppView;

  })(Backbone.View);

  Todos = new TodoList;

  app = new AppView;

}).call(this);
