// Generated by CoffeeScript 1.3.3
(function() {

  define(['jQuery', 'Underscore', 'Backbone', 'models/TodoModel', 'views/TodoView', 'models/TodoList'], function($, _, Backbone, Todo, TodoView, TodoList) {
    var AppView;
    return AppView = Backbone.View.extend({
      el: $('#todoapp'),
      events: {
        'keypress #new-todo': 'handleKeypress',
        'click #clear-completed': 'clearCompleted'
      },
      initialize: function() {
        this.Todos = new TodoList;
        this.Todos.bind('add', this.addTodo, this);
        this.Todos.bind('reset', this.addAll, this);
        this.Todos.bind('all', this.render, this);
        return this.Todos.fetch();
      },
      addAll: function() {
        return this.Todos.each(this.addTodo);
      },
      handleKeypress: function(e) {
        if (e.keyCode === 13) {
          this.Todos.create({
            title: $(e.target).val()
          });
          return $(e.target).val("");
        }
      },
      addTodo: function(model) {
        var view;
        view = new TodoView({
          model: model
        });
        return this.$('#todo-list').append(view.render().el);
      },
      clearCompleted: function() {
        return _.each(this.Todos.done(), function(todo) {
          return todo.destroy();
        });
      }
    });
  });

}).call(this);
