// Generated by CoffeeScript 1.3.3
(function() {

  define(['jQuery', 'Underscore', 'Backbone'], function($, _, Backbone) {
    var TodoView;
    return TodoView = Backbone.View.extend({
      tagName: 'li',
      template: _.template($('#item-template').html()),
      events: {
        "click input": "toggleDone",
        "click a.destroy": "clear",
        "dblclick label": "edit",
        "blur .edit": "editDone"
      },
      initialize: function() {
        if (this.model) {
          return this.model.bind('destroy', this.remove, this);
        }
      },
      render: function() {
        this.$el.html(this.template(this.model.toJSON()));
        return this;
      },
      edit: function() {
        this.$el.addClass('editing');
        return this.$('.edit').focus();
      },
      editDone: function() {
        return this.$el.removeClass('editing');
      },
      toggleDone: function() {
        return this.model.toggle();
      },
      clear: function() {
        console.log('remove?');
        return this.model.clear();
      }
    });
  });

}).call(this);
