// Generated by CoffeeScript 1.3.3
(function() {

  define(['Underscore', 'Backbone'], function(_, Backbone) {
    var Todo;
    return Todo = Backbone.Model.extend({
      defaults: function() {
        return {
          title: "empty todo...",
          order: '',
          done: false
        };
      },
      initialize: function() {},
      toggle: function() {
        return this.save({
          done: !this.get("done")
        });
      },
      clear: function() {
        return this.destroy();
      }
    });
  });

}).call(this);
