// Generated by CoffeeScript 1.3.3
(function() {

  define(['Underscore', 'Backbone', 'libs/backbone-localstorage', 'models/TodoModel'], function(_, Backbone, Store, Todo) {
    var TodoList;
    return TodoList = Backbone.Collection.extend({
      model: Todo,
      localStorage: new Store("todos-backbone"),
      done: function() {
        return this.filter(function(todo) {
          return todo.get("done");
        });
      }
    });
  });

}).call(this);
